export { default as headerBg } from "./images/home/Header.svg"
export { default as Sky } from "./images/home/Sky.svg"
export { default as badgerLogo } from "./images/home/badger-logo.svg"
export { default as headerLogo } from "./images/home/header-logo.svg"
export { default as dummyChart } from "./images/home/dummy-chart.svg"
export { default as leftArrow } from "./images/home/left-arrow.svg"
export { default as rightArrow } from "./images/home/right-arrow.svg"
export { default as btnBg } from "./images/btn-bg.svg"

export  { default as badgerBalanceLogo} from "./images/profile/badgerBalanceLogo.svg"
export  { default as avatar} from "./images/profile/Avatar.svg"

export { default as treeMobile } from "./images/mobile/Trees_mobile.svg"
export { default as treeBgMobile } from "./images/mobile/TreesBg_mobile.svg"
export { default as hillBgMobile } from "./images/mobile/HillBg_mobile.svg"
export { default as groundMobile } from "./images/mobile/Ground_mobile.svg"
export { default as ground2Mobile } from "./images/mobile/Ground2.svg"
export { default as bushesBgMobile } from "./images/mobile/bushesBg_mobile.svg"